### ISSUE TITLE
Branch renaming issue on zsh update

### ISSUE THREAD

**Issue by hyrious** [BuonOmo/yarn-completion#13]
Just noticed an error occured on zsh daily update, which says

```
Failed pulling /Users/hyrious/.oh-my-zsh/custom/plugins/yarn-completion
...... 'refs/heads/master'.
```

Quick solution: goto that folder and change the remote tracking branch to main

```
cd ~/.oh-my-zsh/custom/plugins/yarn-completion
git fetch --all --prune
git branch -M main
git branch -u origin/main
git pull
```

**Comment by BuonOmo** [comment]
Hey, I'm glad the plugin is still used!

I've made **a lot** of changes recently to fix **a lot** of issues. I've taken the opportunity of those breaking changes to also:

- change the repo name
- change from master to main for the origin branch
- require one to have jq to use the completion (to avoid parsing json with sed)

Hence it was likely to break here. Your solution is great, TBH, I'd advise anyone with any problem to just reinstall the plugin from scratch. And I've made [a brew formula](https://github.com/BuonOmo/homebrew-core/commit/eea32a45735f9031ee61c8b788b8104b57c21458) as well if one want to use brew for that.

Since the repo is not yet famous enough, you'd have to:

```sh
brew edit yarn-extra-completion
# copy code
brew install --build-from-source yarn-extra-completion
```

Anyway thanks for the fix. I'll close the issue as I don't think anything is left to do, but for people to view your solution 🙂
