### ISSUE TITLE
oh-my-zsh `yarn run [tab]` completion not working

### ISSUE THREAD

**Issue by jethrolarson** [BuonOmo/yarn-completion#5]
just installed following instructions and opened new iterm 2 terminal and
yarn run [tab] shows
![image](https://user-images.githubusercontent.com/32480/118331160-10e20a80-b4bd-11eb-87fa-51d3e89cc22c.png)

**Comment by BuonOmo** [comment]
@jethrolarson thank you for reporting the issue.

Unfortunately I only started that for my own simple needs by forking `zsh-better-npm-completion`. I won't have any time soon on that project. Please feel free to open a pull request, which I'll review for sure.

Maybe this issue has been reported and fixed in the original repo, in which case, I'd be glad to integrate it
